@IsTest
private class TSTC_CaseNRAOwnerAssignment {
  /*  @isTest static void testCase() {
        Id CanadaAccountRT = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Canada Account').getRecordTypeId();
        
        Test.startTest();
        Case tstCase = new Case();
        tstCase.Subject = 'Test nra 1';
        tstCase.Description = 'Test NRA 1';
        tstCase.RecordTypeId = CanadaAccountRT;
        tstCase.Origin = 'Public Email';
        insert tstCase;
        
    }*/
}